package com.blog.blogservice.util;

public enum ResponseErrorType {
  INVALID_PARAMETER, PARAMETER_REQUIRED, INCOMPATIBLE_VALUES, SERVICE_ERROR, BAD_REQUEST, CLINIC_NOT_FOUND, USER_NOT_FOUND, UNAUTHORIZED, NOT_FOUND, FORBIDDEN, METHOD_NOT_ALLOWED, UNAUTHORIZED_USER, INTERNAL_SERVER_ERROR
}
